# Generated by Django 5.0.6 on 2024-05-25 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='date_opening',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content_type', models.CharField(
                    choices=[('T', 'Text'), ('I', 'Image'), ('V', 'Video'), ('A', 'Audio'), ('F', 'File')], default='T',
                    max_length=1)),
                ('description', models.TextField()),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.box')),
            ],
        ),
        migrations.DeleteModel(
            name='Component',
        ),
    ]
