# Generated by Django 5.0.6 on 2024-05-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_alter_box_date_opening_memory_delete_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='audio_content',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='memory',
            name='file_content',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='memory',
            name='image_content',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='memory',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='video_content',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
