# Generated by Django 5.0.6 on 2024-05-27 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('boxes', '0003_memory_audio_content_memory_file_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='status',
            field=models.CharField(choices=[('E', 'Edited'), ('L', 'Locked'), ('O', 'Opened')], default='E',
                                   max_length=100),
        ),
        migrations.AlterField(
            model_name='box',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
