# Generated by Django 5.0.6 on 2024-05-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0004_box_status_alter_box_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='category',
            field=models.CharField(choices=[('FA', 'Family'), ('TR', 'Travel'), ('FR', 'Friends'), ('LO', 'Love'), ('HO', 'Hobby'), ('O', 'Other')], default='O', max_length=100),
        ),
    ]
